# Generated by Django 3.0.8 on 2020-07-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=50)),
                ('Productcom', models.CharField(max_length=70)),
                ('Productid', models.IntegerField()),
                ('Productmufc', models.CharField(max_length=70)),
                ('Productcost', models.IntegerField()),
            ],
        ),
    ]
